version: '2.0'

services:
 db:
  image: mysql
  command: --default-authentication-plugin=mysql_native_password
  restart: always
  environment:
  #  MYSQL_ROOT_PASSWORD
   MYSQL_DATABASE: student
   MYSQL_USER: studentdbuser
  #  MYSQL_PASSWORD
  # volumes: 
  #  - ./mysqlconf:/etc/mysql/conf.d
  ports:
   - 3306:3306

 adminer:
  image: adminer
  restart: always
  ports:
   - 8080:8080

 web:
  build: .
  command: python manage.py migrate
  command: python manage.py createsuperuser --email admin@example.com --username admin
  command: python manage.py runserver 0.0.0.0:8000
  environment:
   - DEBUG=True
  volumes:
   - .:/code
  ports:
   - "8000:8000"
  depends_on:
   - db
